gave responsive style to the pages
scheme-dojo/scheme-dojo.github.io pull request #14
Opened 2024-07-03 07:19 UTC by rabiarz

2024-07-03 08:20 UTC, mre1ght requested changes

2024-07-03 08:20 UTC, mre1ght commented on hint.css
> +.back-btn a {
please devide class .back-btn and a .
```
.back-btn{
}
a {
}
```

2024-07-03 08:20 UTC, mre1ght commented on hint.css
> +  .back-btn {
This .back-btn should be included in before.

2024-07-03 08:20 UTC, mre1ght commented on index.html
> +        <button class="enter-btn" id="enter-btn" >Enter</button>
Please remove blank.
After
` <button class="enter-btn" id="enter-btn">Enter</button>`

2024-07-03 08:20 UTC, mre1ght commented on index.html
> +      <p class="label-tag" >Question</p>
Please remove blank.
After
`<p class="label-tag">Question</p>`

2024-07-03 08:20 UTC, mre1ght commented on index.css
> +@media (min-width: 800px) {
please add comment before.
Example
```
/* When viewing from a mobile phone*/
@media (min-width: 800px) {
```

2024-07-03 08:20 UTC, mre1ght commented on index.css
>  .image {
This class name .image and .img will make us confused.
.image 
The .image class is responsible for the CSS around the .img.
How about `.img-around` ?
If you have a good name that's OK.

2024-07-03 08:20 UTC, mre1ght commented on index.css
Please delete one line.

2024-07-03 08:20 UTC, mre1ght commented on index.css
>  }
Please insert one line.

2024-07-03 08:20 UTC, mre1ght commented on index.css
Please delete one line.

2024-07-03 08:20 UTC, mre1ght commented on hint.css
>  .title {
The index.css uses the `h1 `class name. 
However, the hint.css uses the `.title `class name. 
Please use one of them.

2024-07-03 11:43 UTC, azamiya commented
# ADA REVIEW

- Eight gonna teach you how to debug page using phone.

- index page design is almost okay. one thing, when I see this page with iPhone, button style was different
![IMG_5678](https://github.com/scheme-dojo/scheme-dojo.github.io/assets/7720795/b702ed89-959d-4c1a-a46b-973a6794b883)

- hint page's button style is OK

![IMG_5679](https://github.com/scheme-dojo/scheme-dojo.github.io/assets/7720795/1b9a77b7-b2e9-493e-bc5d-e6242b763d95)

2024-07-04 03:31 UTC, mre1ght commented on hint.css
> +.back-btn a {
This is my fault.
you don't have to fix this.

2024-07-04 08:34 UTC, mre1ght approved these changes

2024-07-04 08:34 UTC, merged